import { TUser } from "@/types/user";

export const data: TUser[] = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    status: "active",
    address: "123 Main St, New York, NY 10001",
    joined_at: new Date("2023-01-15"),
    notes: "VIP customer, prefers email communication",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    status: "inactive",
    address: "456 Oak Ave, Los Angeles, CA 90210",
    joined_at: new Date("2023-03-22"),
    notes: "Account temporarily suspended",
  },
  {
    id: 3,
    name: "Mike Johnson",
    email: "mike.johnson@example.com",
    status: "active",
    address: "789 Pine Rd, Chicago, IL 60601",
    joined_at: new Date("2022-11-08"),
    notes: "Regular customer, no special requirements",
  },
  {
    id: 4,
    name: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    status: "inactive",
    address: "321 Elm St, Houston, TX 77001",
    joined_at: new Date("2024-01-10"),
    notes: "New user, onboarding in progress",
  },
  {
    id: 5,
    name: "David Brown",
    email: "david.brown@example.com",
    status: "active",
    address: "654 Maple Dr, Phoenix, AZ 85001",
    joined_at: new Date("2023-07-03"),
    notes: "Enterprise client, priority support",
  },
  {
    id: 6,
    name: "Lisa Davis",
    email: "lisa.davis@example.com",
    status: "inactive",
    address: "987 Cedar Ln, Philadelphia, PA 19101",
    joined_at: new Date("2023-05-18"),
    notes: "Payment issues resolved, reactivation pending",
  },
  {
    id: 7,
    name: "Tom Anderson",
    email: "tom.anderson@example.com",
    status: "active",
    address: "147 Birch St, San Antonio, TX 78201",
    joined_at: new Date("2023-09-12"),
    notes: "Frequent user, positive feedback",
  },
  {
    id: 8,
    name: "Emma Taylor",
    email: "emma.taylor@example.com",
    status: "active",
    address: "258 Spruce Ave, San Diego, CA 92101",
    joined_at: new Date("2023-02-28"),
    notes: "Beta tester, provides valuable feedback",
  },
  {
    id: 9,
    name: "Chris Miller",
    email: "chris.miller@example.com",
    status: "inactive",
    address: "369 Willow Ct, Dallas, TX 75201",
    joined_at: new Date("2023-12-05"),
    notes: "Account under review",
  },
  {
    id: 10,
    name: "Anna White",
    email: "anna.white@example.com",
    status: "active",
    address: "741 Aspen Way, San Jose, CA 95101",
    joined_at: new Date("2023-06-14"),
    notes: "Long-term customer, excellent payment history",
  },
];
